#include <iostream.h>
#include <conio.h>
#include <iomanip.h>
#include <cstring>
#ifndef _GRAFIKH
#define _GRAFIKH
class Grafik {
   public:
//      Grafik() { x=5;y =3; }
      int ritakort(HWND hwnd,HINSTANCE hinst, POINT p, int baksida, int farg, int valor);

//      Endast för dos -----------------------
//		  int ritakort(int position, bool markerad=false, int baksida=-1,string text="\0");
//      void markera(int position);
//      void clearscreen(void) { clrscr(); }
//      void skrivtext( int x, int y,char text[50] );
//      void skrivkortmeny(int);
//      void setx( int xx ) { x = xx; }
//      void setyy( int yy ) { y = yy; }
//   private:
//      int x, y;
//      string korttext[5];
//      int kortbaksida[5];
//      Endast för dos -----------------------
};
#endif
