#ifndef _TEXTH
#define _TEXTH
#define ST_GAMETITLE "Netpoker"
#define ST_SATISFIED "Satisfied"
#define ST_SENDMSG "Send Message"
#define ST_NEWGAME "New game"
#define ST_NEXTPLAYER "Next player"
#define ST_CARDS " cards "
#define ST_WINNERCARDS "The winners cards, "
#define ST_PLAYERSTHROW1 "Players that"
#define ST_PLAYERSTHROW2 "thrown cards:"
#define ST_CONNECTEDPLAYERS "Connected players: "
#define ST_ERR_GAMEFULL1 "The game is full or doesn't exist.\nThe Program will terminate."
#define ST_ERR_GAMEFULL2 "Game not found. Program will terminate."
#define ST_ERR_GAMEFULL3 "No game found"
#define ST_ERR_NOTTHROW "You can not throw cards until you retrive new ones."
#define ST_THROWCARDS "Throw cards"
#define ST_WAIT "Wait..."
#define ST_WAITFORCARDS "Wait until all players thrown their cards, then you will retrive new"
#define ST_WAITFORPLAYERS "Wait until all players has connected to the game"
#define ST_NEWGAMESTARTED "A new game has started. New cards for everyone."
#define ST_WAITFORCONNECTIONS "Wait until all players has connected to the game."
#define ST_INFONEWGAME "Press on New game, to start the game"
#define ST_CONTTOPLAY "Do you want to continue to play?"
#define ST_PLAYER "Player "
#define ST_THREW " threw "
#define ST_CARDSDOT " cards."
#define ST_SENDACCEPT "One player has connected to the game."
#define ST_INFOWAITFORPLAYERS "Waiting for players that want to connect..."
#define ST_ISCONNECTED " connected."
#define ST_DISCONNECT " disconnected."
#define ST_ACCEPTED "You have been accepted to participate in the game"
#define ST_INFOWAITFORGAME "Wait until a new game is started."
#define ST_CLOSEDCONNECTION1 "The game suddenly ended.\n This program will terminate"
#define ST_CLOSEDCONNECTION2 "The game was interrupted!"

#define ST_TYPEOFGAME "Type of game"
#define ST_IGIVE "&Create game"
#define ST_CONNECTTOGAME "&Join game"
#define ST_YOURNAME "Your name:"
#define ST_OK "Ok"
#define ST_QUIT "&Quit"
#define ST_IPHOST "IP-number/Host"
#define ST_IP "IP-number or Host:"
#define ST_HOST "Host"
#define ST_ABOUT "About Netpoker"
#define ST_ABOUTSWE "Om NätPoker"
#define ST_ASKCONTINUE "Do you want to try again?"

#define ST_WELCOME "Welcome to th netpoker now you can just wait until the creator of the game starts the game."
#define ST_FILE "&File"
#define ST_NEW "&New"
#define ST_HELP "&Help"
#endif
